# Generated by Django 5.2.2 on 2025-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(choices=[('card-1', 'card-1'), ('card-2', 'card-2'), ('card-3', 'card-3'), ('card-4', 'card-4')], default='unique', max_length=10)),
                ('card_name', models.CharField(max_length=50)),
                ('card_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='air_quality',
        ),
        migrations.DeleteModel(
            name='battery_voltage',
        ),
        migrations.DeleteModel(
            name='frequency',
        ),
        migrations.DeleteModel(
            name='ph',
        ),
        migrations.DeleteModel(
            name='Pressure',
        ),
    ]
