# Generated by Django 5.2.2 on 2025-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_card_delete_air_quality_delete_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(choices=[('card-1', 'card-1'), ('card-2', 'card-2'), ('card-3', 'card-3'), ('card-4', 'card-4')], max_length=10, unique=True),
        ),
    ]
